### ISSUE TITLE
classname completion kills rljdb

### ISSUE THREAD

**Issue by hokuda** [hokuda/rljdb#7]
break sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(java.security.cert.X509Certificate[],java.lang.String,java

**Comment by hokuda** [comment]
~~~
> break sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(java.security.cert.X509Certificate[],java.lang.String,javaTraceback (most recent call last):
  File "/home/hokuda/src/github.com/hokuda/rljdb/rljdb_filter", line 1228, in <module>
    rlwrap_filter.run()
  File "/home/local/share/rlwrap/filters/rlwrapfilter.py", line 577, in run
    completions = self.completion_handler(line, prefix, completions)
  File "/home/hokuda/src/github.com/hokuda/rljdb/rljdb_filter", line 1136, in completion_handler
    request = executor.completion_handler(CompletionRequest(line, prefix, completions))
  File "/home/hokuda/src/github.com/hokuda/rljdb/rljdb_filter", line 198, in completion_handler
    request = self.next.completion_handler(request)
  File "/home/hokuda/src/github.com/hokuda/rljdb/rljdb_filter", line 198, in completion_handler
    request = self.next.completion_handler(request)
  File "/home/hokuda/src/github.com/hokuda/rljdb/rljdb_filter", line 196, in completion_handler
    request = self.handle_completion(request)
  File "/home/hokuda/src/github.com/hokuda/rljdb/rljdb_filter", line 305, in handle_completion
    methods = self.complete_methods(class_name, tail, paren)
  File "/home/hokuda/src/github.com/hokuda/rljdb/rljdb_filter", line 413, in complete_methods
    return list(filter((lambda x: re.search(pattern , x)), methods))
  File "/home/hokuda/src/github.com/hokuda/rljdb/rljdb_filter", line 413, in <lambda>
    return list(filter((lambda x: re.search(pattern , x)), methods))
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib64/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib64/python3.6/sre_parse.py", line 523, in _parse
    source.tell() - here)
sre_constants.error: unterminated character set at position 57
rlwrap: error: EOF reading from filter
rlwrap: warning: filter died
~~~

**Comment by hokuda** [comment]
~~~
 * 412         pattern = r'^' + tail + paren.replace(' ', '').replace('(', '\(').replace(')', '\)')
>  413         return list(filter((lambda x: re.search(pattern , x)), methods))

>>> print(pattern)
^checkAdditionalTrust\(java.security.cert.X509Certificate[],java.lang.String,java
012345678901234567890123456789012345678901234567890123456^
~~~

~~~
>>> import re
>>> re.search(r"hog[]", "hoge")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib64/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib64/python3.6/sre_parse.py", line 523, in _parse
    source.tell() - here)
sre_constants.error: unterminated character set at position 3
>>> 
~~~

**Comment by hokuda** [comment]
fixed
